---
kind: pipeline
type: kubernetes
name: build
steps:
- name: image
  image: images.home.mtaylor.io/drone-kaniko:latest
  settings:
    repo: images.home.mtaylor.io/deployer
    auto_tag: true
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    registry:
      from_secret: registry_url
image_pull_secrets:
- dockerconfigjson
---
kind: secret
name: dockerconfigjson
get:
  path: image-pull-secret
  name: .dockerconfigjson
---
kind: secret
name: registry_username
get:
  path: image-registry
  name: username
---
kind: secret
name: registry_password
get:
  path: image-registry
  name: password
---
kind: secret
name: registry_url
get:
  path: image-registry
  name: url
